/* alike.java */
/* Generated By:JavaCC: Do not edit this line. alike.java */
package traductor;

//...

import lib.symbolTable.*;
import lib.attributes.*;
import lib.symbolTable.exceptions.*;
import java.util.ArrayList;
import java.util.Collections;
import lib.errores.*;
import lib.tools.SemanticFunctions;
import lib.tools.codeGeneration.*;
import static lib.symbolTable.Symbol.Types.*;
import java.io.*;

public class alike implements alikeConstants {


        static SymbolTable st;
        static SemanticFunctions sf = new SemanticFunctions();
        static ArrayList<Token> tipoReturn = new ArrayList<Token>();

        static int linea = 0;

        private static void initSymbolTable() {
                boolean b;
                String[] palsRes = {
                "array","boolean","character","integer","procedure","if","then","elsif","else","end",
                        "while","loop","begin","ref","of","is","not","put_line","put","return","and","or",
                        "mod","skip_line","function","null","get","true","false","int2char","char2int"
                };

                st = new SymbolTable();

                st.insertReservedWords(palsRes);
        }

   public static void main(String[] args) {
           alike parser = null;
           initSymbolTable();

           try {
                   if(args.length == 0) {
                           parser = new alike(System.in);
                   }
                   else {
                           parser = new alike(new java.io.FileInputStream(args[0]));
                   }
                   //Programa es el símbolo inicial de la gramática
                   parser.Programa(args[0]);
                   //...
                   System.out.println("***** An\u00e1lisis terminado con \u00e9xito *****");
           }
           catch (java.io.FileNotFoundException e) {
                   System.err.println ("Fichero " + args[0] + " no encontrado.");
           }
           catch (TokenMgrError e) {
                   System.err.println("LEX_ERROR: " + e.getMessage());
           }
           catch (ParseException e) {
            System.err.println("PARSER_ERROR: " + e.getMessage());
        }
                catch (ErrorSemantico e) {
                        System.err.println("SEMANTIC_ERROR: " + e.getMessage());
                        System.err.println("***** An\u00e1lisis parado por un error *****");
                }
           //...
   }

//------------ Símbolo inicial de la gramática. Para análisis léxico no hace falta más
  static final public void Programa(String filename) throws ParseException {Token name;
        Attributes at = new Attributes();

        CodeBlock cprog=new CodeBlock(), cprocvar=new CodeBlock(),cprocfun=new CodeBlock(),cbloque=new CodeBlock();
cprog = new CodeBlock();
                String etiq = CGUtils.newLabel();
                CGUtils.initializeCGUtils();
    jj_consume_token(tPROC);
    name = jj_consume_token(tID);
try{
                        name.image = name.image.toLowerCase();
                        if(!st.isReservedWord(name.image))
                        {
                                st.insertReservedWord(name.image);

                                SymbolProcedure S = new SymbolProcedure(name.image, at.parList);
                                st.insertSymbol(S);
                        }
                        else
                        {
                                {if (true) throw new ErrorSemantico("ID no valido. Es una palabra reservada");}
                        }
                } catch (AlreadyDefinedSymbolException ex)
                {
                        {if (true) throw new ErrorSemantico("Simbolo ya existente");}
                }
    jj_consume_token(tIS);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tID:{
      declaracion_variables(cprocvar, false);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tPROC:
    case tFUNC:{
      label_1:
      while (true) {
        declaracion_procs_funcs(cprocfun);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case tPROC:
        case tFUNC:{
          ;
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          break label_1;
        }
      }
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(tBEGIN);
    instrucciones(cbloque);
    jj_consume_token(tEND);
    jj_consume_token(tPC);
//System.err.println("Bloque " + name.image + " terminado \n" + st.toString());
                cprog.addInst(PCodeInstruction.OpCode.ENP, etiq);
                cprog.addBlock(cprocvar);
                cprog.addBlock(cprocfun);
                cprog.addComment("Comienzo main");
                cprog.addLabel(etiq);
                cprog.addBlock(cbloque);
                cprog.addComment("Fin main");
                cprog.addInst(PCodeInstruction.OpCode.LVP);
                //System.out.println(cprog.toString());

                File f = new File(filename);

                String fName = f.getName();
                int pos = fName.lastIndexOf(".");
                if (pos > 0) {
                        fName = fName.substring(0, pos);
                }

                f = new File(fName+".pcode");

                try{
                        BufferedWriter writer = new BufferedWriter(new FileWriter(f));
                        writer.write(cprog.toString());
                        writer.close();
                } catch(IOException ex)
                {
                        System.err.println("Error en la escritura a fichero");
                }
}

  static final public void declaracion_procedimiento(CodeBlock cBlock) throws ParseException {Token name;
        Attributes att = new Attributes();

        CodeBlock cprog=new CodeBlock(),cparam = new CodeBlock(),cprocfun=new CodeBlock(),cprocvar=new CodeBlock(),cbloque=new CodeBlock();
        CGUtils.addLevel();
        String etiq = CGUtils.newLabel();
    name = cabecera_procedimiento(att, cparam);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tID:{
      declaracion_variables(cprocvar, false);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tPROC:
    case tFUNC:{
      declaracion_procs_funcs(cprocfun);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
try{
                SymbolProcedure S = (SymbolProcedure) st.getSymbol(name.image);
                S.etiq = etiq;
                }catch(SymbolNotFoundException ex)
                {
                        {if (true) throw new ErrorSemantico(name.image + " no existe.");}
                }
    jj_consume_token(tBEGIN);
    instrucciones(cbloque);
    jj_consume_token(tEND);
    jj_consume_token(tPC);
//System.err.println("Bloque " + name.image + " terminado \n" + st.toString());
                st.removeBlock();
                CGUtils.removeLevel();

                cprog.addComment("Comienzo procedure "+name.image);
                cprog.addLabel(etiq);
                cprog.addBlock(cparam);

                String labelCode = CGUtils.newLabel();
                cprog.addInst(PCodeInstruction.OpCode.JMP,labelCode);

                cprog.addBlock(cprocvar);
                cprog.addBlock(cprocfun);

                cprog.addLabel(labelCode);
                cprog.addBlock(cbloque);
                cprog.addComment("Fin procedure "+name.image);
                cprog.addInst(PCodeInstruction.OpCode.CSF);
                cBlock.addBlock(cprog);
}

  static final public void declaracion_funcion(CodeBlock cBlock) throws ParseException {Attributes atType = new Attributes();
        Attributes atIsArray = new Attributes();
        Attributes atts = new Attributes();
        Token name;
        String etiq = CGUtils.newLabel();
        CodeBlock cprog=new CodeBlock(),cparam = new CodeBlock(), cprocvar=new CodeBlock(),cprocfun=new CodeBlock(),cbloque=new CodeBlock();
        CGUtils.addLevel();
    name = cabecera_funcion(atType,atIsArray,atts, cparam);
tipoReturn.add(name);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tID:{
      declaracion_variables(cprocvar, false);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tPROC:
    case tFUNC:{
      declaracion_procs_funcs(cprocfun);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(tBEGIN);
try{
                SymbolFunction S = (SymbolFunction) st.getSymbol(name.image);
                S.etiq = etiq;
                }catch(SymbolNotFoundException ex)
                {
                        {if (true) throw new ErrorSemantico(name.image + " no existe.");}
                }
    instrucciones(cbloque);
    jj_consume_token(tEND);
    jj_consume_token(tPC);
//System.err.println("Bloque " + name.image + " terminado \n"+ st.toString());
                st.removeBlock();
                CGUtils.removeLevel();

                if(atType.type == Symbol.Types.ARRAY)
                {
                        {if (true) throw new ErrorSemantico("No se permiten funciones con retorno de vectores");}
                }

                tipoReturn.remove(tipoReturn.size()-1);

                cprog.addComment("Comienzo function "+name.image);
                cprog.addLabel(etiq);
                cprog.addBlock(cparam);

                String labelCode = CGUtils.newLabel();
                cprog.addInst(PCodeInstruction.OpCode.JMP,labelCode);

                cprog.addBlock(cprocvar);
                cprog.addBlock(cprocfun);

                cprog.addLabel(labelCode);

                cprog.addBlock(cbloque);
                cprog.addComment("Fin function "+name.image);
                cprog.addInst(PCodeInstruction.OpCode.CSF);
                cBlock.addBlock(cprog);
}

  static final public void declaracion_procs_funcs(CodeBlock cBlock) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tPROC:{
      declaracion_procedimiento(cBlock);
      break;
      }
    case tFUNC:{
      declaracion_funcion(cBlock);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void instrucciones(CodeBlock cBlock) throws ParseException {CodeBlock cInst = new CodeBlock();
    label_2:
    while (true) {
      instruccion(cInst);
cBlock.addBlock(cInst);
                cInst = new CodeBlock();
      jj_consume_token(tPC);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tIF:
      case tWHILE:
      case tPLINE:
      case tPUT:
      case tRETURN:
      case tSKIP:
      case tNULL:
      case tGET:
      case tID:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_2;
      }
    }
}

  static final public void declaracion_variables(CodeBlock cprocvar, Boolean esParametro) throws ParseException {
    label_3:
    while (true) {
      declaracion_var(cprocvar, esParametro);
      jj_consume_token(tPC);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tID:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_3;
      }
    }
}

  static final public ArrayList<Symbol> declaracion_var(CodeBlock cprocvar, Boolean esParametro) throws ParseException {Attributes atType = new Attributes();
        Attributes atIsArray = new Attributes();
        ArrayList<Token> tokens;
        ArrayList<Symbol> symbols = new ArrayList<Symbol>();
    tokens = lista_ids();
    jj_consume_token(tDP);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tREF:{
      jj_consume_token(tREF);
atType.parClass = Symbol.ParameterClass.REF;
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    tipo_variable(atType,atIsArray);
if(atType.parClass==Symbol.ParameterClass.NONE)atType.parClass=Symbol.ParameterClass.VAL;
                        for(Token t : tokens)
                        {
                                Symbol S = null;


                                //System.out.println(atType.type + " " + atIsArray.type);
                                if(atType.type == Symbol.Types.BOOL) S = new SymbolBool(t.image, atType.parClass);
                                if(atType.type == Symbol.Types.CHAR) S = new SymbolChar(t.image, atType.parClass);
                                if(atType.type == Symbol.Types.INT) S = new SymbolInt(t.image, atType.parClass);
                                if(atType.type == Symbol.Types.ARRAY)
                                {
                                        if(atType.inicio>atType.fin)
                                        {
                                                {if (true) throw new ErrorSemantico("Indices en declaraci\u00f3n de array incoherentes");}
                                        }

                                        S = new SymbolArray(t.image, atType.inicio,atType.fin,atIsArray.type,atType.parClass);
                                }
                                symbols.add(S);


                                try {

                                        String name = "";
                                        Symbol.Types type = Symbol.Types.UNDEFINED;
                                        long inicio=0, fin = 0;
                                        if(S.type == Symbol.Types.ARRAY) {
                                                inicio = CGUtils.getDir();
                                                S.dir = inicio;
                                                if(S.parClass != Symbol.ParameterClass.REF){
                                                        for (int i = atType.inicio+1; i < atType.fin; i++) {
                                                                fin = CGUtils.getDir();
                                                        }
                                                        fin = CGUtils.getDir();
                                                }
                                                name = "Array";
                                                SymbolArray symbolArrayInstance = (SymbolArray) S;
                                                type = symbolArrayInstance.baseType;
                                                if(!esParametro) cprocvar.addComment("- " + name + " variable \"" + t.image + "\", type " + type + ", size " + ( symbolArrayInstance.maxInd-symbolArrayInstance.minInd+1) +", level " + st.level + ", address [" + inicio + ":" + fin + "]!");
                                                else {
                                                        if(S.parClass == Symbol.ParameterClass.REF) cprocvar.addComment("- " + name +" parameter \"" + t.image + "\", type " + type + ", size " + ( symbolArrayInstance.maxInd-symbolArrayInstance.minInd+1) + ", class " + S.parClass + ", level " + st.level + ", address ["+S.dir+"]!");
                                                        else
                                                        cprocvar.addComment("- " + name +" parameter \"" + t.image + "\", type " + type + ", size " + ( symbolArrayInstance.maxInd-symbolArrayInstance.minInd+1) + ", class " + S.parClass + ", level " + st.level + ", address [" + inicio + ":" + fin + "]!");
                                                }
                                        } else {
                                        S.dir = CGUtils.getDir();
                                        if(!esParametro && S.type != Symbol.Types.ARRAY) {type = S.type; cprocvar.addComment("- Simple variable \"" + t.image + "\", type " + type + ", level " + st.level + ", address [" + S.dir + "]!");}
                                        else {type = S.type;cprocvar.addComment("- Simple parameter \"" + t.image + "\", type " + type + ", class " + S.parClass + ", level " + st.level + ", address [" + S.dir + "]!");}
                                        }
                                        st.insertSymbol(S);
                                } catch (AlreadyDefinedSymbolException e)
                                {
                                        {if (true) throw new ErrorSemantico("Error semantico. Simbolo ya existente");}
                                }
                        }

                        {if ("" != null) return symbols;}
    throw new Error("Missing return statement in function");
}

  static final public Attributes lista_componentes() throws ParseException {Token t;
        Attributes att = new Attributes();
        Attributes at = new Attributes();
        Symbol S = null;
        CodeBlock cBlock = new CodeBlock();
    t = jj_consume_token(tID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:{
      jj_consume_token(tAP);
      expresion(at, cBlock);
      jj_consume_token(tCP);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
t.image = t.image.toLowerCase();
                                if(!st.isReservedWord(t.image))
                                {
                                        try
                                        {
                                                t.image = t.image.toLowerCase();
                                                S = st.getSymbol(t.image);
                                                sf.cambiarTipos(at, S);
                                                sf.asignar_valores(att,at,t.image,S.type, S.parClass, st.level,false);
                                                //sf.checkPrimarioIds(at);
                                                at = new Attributes();
                                        }
                                        catch(SymbolNotFoundException ex)
                                        {
                                                {if (true) throw new ErrorSemantico(t.image + " no existe.");}
                                        }
                                }
                                else
                                {
                                        {if (true) throw new ErrorSemantico("ID no valido. Es una palabra reservada");}
                                }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tCOMA:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
      jj_consume_token(tCOMA);
      t = jj_consume_token(tID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tAP:{
        jj_consume_token(tAP);
        expresion(at, cBlock);
        jj_consume_token(tCP);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        ;
      }
t.image = t.image.toLowerCase();
                                if(!st.isReservedWord(t.image))
                                {
                                        try
                                        {
                                                t.image = t.image.toLowerCase();
                                                S = st.getSymbol(t.image);
                                                sf.cambiarTipos(at, S);
                                                sf.asignar_valores(att,at,t.image,S.type, S.parClass, st.level,false);
                                                //sf.checkPrimarioIds(at);
                                                at = new Attributes();
                                        }
                                        catch(SymbolNotFoundException ex)
                                        {
                                                {if (true) throw new ErrorSemantico(t.image + " no existe.");}
                                        }
                                }
                                else
                                {
                                        {if (true) throw new ErrorSemantico("ID no valido. Es una palabra reservada");}
                                }
    }
//System.err.println("Lista de ids ");
                        {if ("" != null) return att;}
    throw new Error("Missing return statement in function");
}

  static final public ArrayList<Token> lista_ids() throws ParseException {ArrayList<Token> tokens = new ArrayList<Token>();
        Token t;
    t = jj_consume_token(tID);
t.image = t.image.toLowerCase();
                                if(!st.isReservedWord(t.image))
                                {
                                        tokens.add(t);
                                }
                                else
                                {
                                        {if (true) throw new ErrorSemantico("ID no valido. Es una palabra reservada");}
                                }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tCOMA:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      jj_consume_token(tCOMA);
      t = jj_consume_token(tID);
t.image = t.image.toLowerCase();
                                if(!st.isReservedWord(t.image)) tokens.add(t);
                                else {if (true) throw new ErrorSemantico("ID no valido. Es una palabra reservada");}
    }
//System.err.println("Lista de ids ");
                        {if ("" != null) return tokens;}
    throw new Error("Missing return statement in function");
}

  static final public void lista_ids_o_string_o_inv(Attributes att, CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();
    expresion(at, cBlock);
att.atts.add(at.clone());
                switch (at.type){
                        case STRING:
                                String code = at.code;
                                if (code.startsWith("\"") && code.endsWith("\"")) {
                                        code = code.substring(1, code.length() - 1);
                                }
                                if (code.contains("\"\"")) {
                                        code = code.replace("\"\"", "\"");
                                }
                                cBlock.addComment("- Write STRING \"" + code + "\".");
                                for(char c: code.toCharArray()) {
                                        cBlock.addComment("- Write CHAR \"" + c + "\".");
                                        cBlock.addInst(PCodeInstruction.OpCode.STC, (int)c);
                                        cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
                                }
                                break;
                        case CHAR:
                                cBlock.addComment("- Write CHAR \"" + at.code + "\".");

                                if(!at.code.contains("int2char"))
                                {
                                        //cBlock.addInst(PCodeInstruction.OpCode.STC, (int)at.code.charAt(0));
                                        cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
                                } else {
                                        cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
                                }
                                break;

                }

                at = new Attributes();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tCOMA:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_6;
      }
      jj_consume_token(tCOMA);
      expresion(at, cBlock);
att.atts.add(at.clone());
                switch (at.type){
                        case STRING:
                                String code = at.code;
                                if (code.startsWith("\"") && code.endsWith("\"")) {
                                        code = code.substring(1, code.length() - 1);
                                }
                                if (code.contains("\"\"")) {
                                        code = code.replace("\"\"", "\"");
                                }
                                cBlock.addComment("- Write STRING \"" + code + "\".");
                                for(char c: code.toCharArray()) {
                                        cBlock.addComment("- Write CHAR \"" + c + "\".");
                                        cBlock.addInst(PCodeInstruction.OpCode.STC, (int)c);
                                        cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
                                }
                                break;
                        case CHAR:
                                if(!at.code.contains("int2char"))
                                {
                                        cBlock.addComment("- Write CHAR \"" + at.code + "\".");
                                        //cBlock.addInst(PCodeInstruction.OpCode.STC, (int)at.code.charAt(0));
                                        cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
                                } else {
                                        cBlock.addComment("- Write CHAR \"" + at.code + "\".");
                                }

                                break;

                }

                at = new Attributes();
    }
att.type = att.atts.get(0).type;
}

  static final public Token cabecera_procedimiento(Attributes att, CodeBlock cprog) throws ParseException {Token name;
        String lbel = CGUtils.newLabel();
    jj_consume_token(tPROC);
    name = jj_consume_token(tID);
try {
                        name.image = name.image.toLowerCase();
                        Symbol S = new SymbolProcedure(name.image,att.parList);
                        st.insertSymbol(S);
                        st.insertBlock();
                }catch (AlreadyDefinedSymbolException ex)
                {
                        {if (true) throw new ErrorSemantico("Error semantico. Simbolo ya existente");}
                }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:{
      jj_consume_token(tAP);
      parametros_formales(att, cprog);
      jj_consume_token(tCP);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    jj_consume_token(tIS);
{if ("" != null) return name;}
    throw new Error("Missing return statement in function");
}

  static final public Token cabecera_funcion(Attributes atType,Attributes atIsArray,Attributes atts, CodeBlock cprog) throws ParseException {Token name;
        SymbolFunction S = null;
    jj_consume_token(tFUNC);
    name = jj_consume_token(tID);
try{
                        name.image = name.image.toLowerCase();
                        S = new SymbolFunction(name.image,atts.parList,atType.type);
                        st.insertSymbol(S);
                        st.insertBlock();
                } catch (AlreadyDefinedSymbolException ex)
                {
                        {if (true) throw new ErrorSemantico("Error semantico. Simbolo ya existente");}
                }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:{
      jj_consume_token(tAP);
      parametros_formales(atts, cprog);
      jj_consume_token(tCP);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(tRETURN);
    tipo_variable_simple(atType);
    jj_consume_token(tIS);
S.returnType = atType.type;
                {if ("" != null) return name;}
    throw new Error("Missing return statement in function");
}

  static final public void parametros_formales(Attributes att, CodeBlock cprog) throws ParseException {ArrayList<Symbol> symbols;
        CodeBlock cprocvar = new CodeBlock();
        CodeBlock auxBlock = new CodeBlock();
        CodeBlock auxBlock1 = new CodeBlock();
        CodeBlock auxBlock2 = new CodeBlock();
        boolean rightSweepingSide = true;
    symbols = declaracion_var(cprocvar, true);
// try {

                        cprog.addBlock(cprocvar);
                        cprocvar = new CodeBlock();

                        for (int j = symbols.size() - 1; j >= 0; j--) {
                                // whatever
                                Symbol S = symbols.get(j);

                                att.parList.add(S);

                                if(S instanceof SymbolArray && S.parClass!=Symbol.ParameterClass.REF)
                                {
                                        SymbolArray SA = (SymbolArray) S;

                                        for(int i = SA.maxInd-SA.minInd+1;i>0;i--)
                                        {
                                                auxBlock1.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir+i);
                                                auxBlock1.addInst(PCodeInstruction.OpCode.ASGI);
                                        }
                                }
                                else
                                {
                                        auxBlock1.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);
                                        auxBlock1.addInst(PCodeInstruction.OpCode.ASGI);
                                }
                        }

                        auxBlock = auxBlock1;


                // } catch (AlreadyDefinedSymbolException ex)
                // {
                // 	System.err.println("Error semantico. Simbolo ya existente");
                // }

    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tPC:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_7;
      }
      jj_consume_token(tPC);
      symbols = declaracion_var(cprocvar, true);
cprog.addBlock(cprocvar);
                cprocvar = new CodeBlock();

                for (int j = symbols.size() - 1; j >= 0; j--) {
                        // whatever
                        Symbol S = symbols.get(j);

                        att.parList.add(S);

                        if(S instanceof SymbolArray && S.parClass!=Symbol.ParameterClass.REF)
                        {
                                SymbolArray SA = (SymbolArray) S;

                                for(int i = SA.maxInd-SA.minInd+1;i>0;i--)
                                {
                                        if(rightSweepingSide)
                                        {
                                                auxBlock2.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir+i);
                                                auxBlock2.addInst(PCodeInstruction.OpCode.ASGI);
                                        }
                                        else
                                        {
                                                auxBlock1.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir+i);
                                                auxBlock1.addInst(PCodeInstruction.OpCode.ASGI);
                                        }
                                }
                        }
                        else
                        {
                                if(rightSweepingSide)
                                {
                                        auxBlock2.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);
                                        auxBlock2.addInst(PCodeInstruction.OpCode.ASGI);
                                }
                                else
                                {
                                        auxBlock1.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);
                                        auxBlock1.addInst(PCodeInstruction.OpCode.ASGI);
                                }
                        }
                }

                if(rightSweepingSide)
                {
                        auxBlock2.addBlock(auxBlock1);
                        auxBlock = auxBlock2;
                }
                else
                {
                        auxBlock1.addBlock(auxBlock2);
                        auxBlock = auxBlock1;
                }

                rightSweepingSide = !rightSweepingSide;
    }
cprog.addBlock(auxBlock);
}

  static final public void instruccion(CodeBlock cBlock) throws ParseException {Attributes att = new Attributes();
        CodeBlock cInst = new CodeBlock();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tGET:{
      inst_leer(att,cInst);
      break;
      }
    case tSKIP:{
      inst_saltar_linea(att,cInst);
      break;
      }
    case tPUT:{
      inst_escribir(att,cInst);
      break;
      }
    case tPLINE:{
      inst_escribir_linea(att,cInst);
      break;
      }
    case tID:{
      inst_invocacion_o_asignacion(att,cInst);
      break;
      }
    case tIF:{
      inst_if(att,cInst);
      break;
      }
    case tWHILE:{
      inst_while(att,cInst);
      break;
      }
    case tRETURN:{
      inst_return(att,cInst);
      break;
      }
    case tNULL:{
      inst_null(att,cInst);
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
//System.out.println(cInst.toString());
                cBlock.addBlock(cInst);
}

  static final public void inst_leer(Attributes att,CodeBlock cBlock) throws ParseException {
    jj_consume_token(tGET);
    jj_consume_token(tAP);
    att = lista_componentes();
    jj_consume_token(tCP);
sf.check_inst_leer(st,att);
for (Attributes a : att.atts)
                {
                        try{
                                Symbol S = st.getSymbol(a.code);
                                cBlock.addComment("- Get simple variable/parameter \"" + a.code + "\".");
                                cBlock.addInst(PCodeInstruction.OpCode.SRF, (st.level - S.nivel), (int)S.dir);
                                cBlock.addInst(PCodeInstruction.OpCode.RD, a.type== Symbol.Types.INT?1:0);
                        } catch (SymbolNotFoundException ex)
                        {
                                {if (true) throw new ErrorSemantico(a.code + " no existe.");}
                        }
                }
}

  static final public void inst_saltar_linea(Attributes att,CodeBlock cBlock) throws ParseException {
    jj_consume_token(tSKIP);
String et = CGUtils.newLabel();
                cBlock.addLabel(et);
                long dir = CGUtils.getDir();
                cBlock.addInst(PCodeInstruction.OpCode.SRF, 0, (int)dir);
                cBlock.addInst(PCodeInstruction.OpCode.RD, 0);
                cBlock.addInst(PCodeInstruction.OpCode.SRF, 0, (int)dir);
                cBlock.addInst(PCodeInstruction.OpCode.DRF);
                cBlock.addInst(PCodeInstruction.OpCode.STC, 10);
                cBlock.addInst(PCodeInstruction.OpCode.EQ);
                cBlock.addInst(PCodeInstruction.OpCode.JMF, et);
}

  static final public void inst_escribir(Attributes att,CodeBlock cBlock) throws ParseException {
    jj_consume_token(tPUT);
    jj_consume_token(tAP);
    lista_ids_o_string_o_inv(att, cBlock);
    jj_consume_token(tCP);
sf.check_inst_escribir(st,att);
                //cBlock.addComment("- Write CR/LF");
                /*cBlock.addInst(PCodeInstruction.OpCode.STC, 13);
		cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
		cBlock.addInst(PCodeInstruction.OpCode.STC, 10);
		cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);*/
                //System.err.println("Expresion: " + att);

}

  static final public void inst_escribir_linea(Attributes att,CodeBlock cBlock) throws ParseException {
    jj_consume_token(tPLINE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:{
      jj_consume_token(tAP);
      lista_ids_o_string_o_inv(att, cBlock);
      jj_consume_token(tCP);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
if(att.atts.size()>0)
                {
                        sf.check_inst_escribir(st,att);
                }
                cBlock.addComment("- Write CR/LF");
                cBlock.addInst(PCodeInstruction.OpCode.STC, 13);
                cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
                cBlock.addInst(PCodeInstruction.OpCode.STC, 10);
                cBlock.addInst(PCodeInstruction.OpCode.WRT, 0);
}

  static final public void inst_invocacion_o_asignacion(Attributes att,CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();
        Attributes at2 = new Attributes();
        Symbol S = null;
        Token t;
    t = jj_consume_token(tID);
try {
                        t.image = t.image.toLowerCase();
                        S = st.getSymbol(t.image);

                } catch (SymbolNotFoundException ex)
                {
                        {if (true) throw new ErrorSemantico(t.image + " no existe.");}
                }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:{
      jj_consume_token(tAP);
      function_call(at2,cBlock,S);
      jj_consume_token(tCP);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
//System.err.println("Tipo de la funcion: " + at2);	
                        sf.cambiarTipos(at2, S);
                        //System.err.println("Tipo de la funcion: " + at2);	
                        sf.asignar_valores(att,at2,t.image,S.type, S.parClass, st.level,false);
                        if(at2.type==Symbol.Types.ARRAY)
                        {
                                {if (true) throw new ErrorSemantico("No se puede realizar una asignaci\u00f3n a un array entero");}
                        }
                        sf.checkTypeFunctionCall(at2);

                        for(int i = 0; i<at2.atts.size(); i++)
                        {
                                System.out.println("\t"+at2.atts.get(i).parClass);
                        }

                        if(S.type == Symbol.Types.PROCEDURE)
                        {
                                SymbolProcedure SP = (SymbolProcedure) S;
                                cBlock.addOSFInst(CGUtils.getInvocDir(),st.level-S.nivel,SP.etiq);
                        }

                        if(S.type == Symbol.Types.FUNCTION)
                        {
                                SymbolFunction SF = (SymbolFunction) S;
                                cBlock.addOSFInst(CGUtils.getInvocDir(),st.level-S.nivel,SF.etiq);
                        }

                        if(S.type == Symbol.Types.ARRAY)
                        {
                                SymbolArray SA = (SymbolArray) S;

                                if(SA.minInd<0)
                                {
                                        cBlock.addInst(PCodeInstruction.OpCode.STC,-SA.minInd);
                                        cBlock.addInst(PCodeInstruction.OpCode.NGI);
                                        cBlock.addInst(PCodeInstruction.OpCode.SBT);
                                }
                                else if(SA.minInd>0)
                                {
                                        cBlock.addInst(PCodeInstruction.OpCode.STC,SA.minInd);
                                        cBlock.addInst(PCodeInstruction.OpCode.SBT);
                                }


                        }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tASIG:{
      jj_consume_token(tASIG);
cBlock.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);

                if(S.parClass==Symbol.ParameterClass.REF)
                {
                        cBlock.addInst(PCodeInstruction.OpCode.DRF);
                }

                if(S instanceof SymbolArray)
                {
                        SymbolArray SA = (SymbolArray) S;

                        cBlock.addInst(PCodeInstruction.OpCode.PLUS);

                }
      expresion(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                sf.checkTypesAsignacion(at,at2);
                at = new Attributes();
                at2 = new Attributes();

                cBlock.addInst(PCodeInstruction.OpCode.ASG);
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      ;
    }

}

  static final public void inst_if(Attributes att,CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();
        CodeBlock cbloque=new CodeBlock();

        String endLabel = CGUtils.newLabel();
        String lbel = null;
    jj_consume_token(tIF);
    expresion(at, cBlock);
if(at.type==Symbol.Types.ARRAY)
                {
                        Attributes aux = at.atts.get(0);
                        for(int i=0; i<6 && aux.atts.size()>0; i++)
                        {
                                aux = aux.atts.get(0);
                        }
                        if(aux.type!=Symbol.Types.INT)
                        {
                                {if (true) throw new ErrorSemantico("No puedes comparar un array entero con un booleano");}
                        }
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("El array tienen que devolver un booleano: "+at.type);}
                        }
                }
                else if(at.type== Symbol.Types.FUNCTION)
                {
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("La funcion tienen que devolver un booleano: "+at.type);}
                        }
                }
                else if(at.type!=Symbol.Types.BOOL)
                {
                        {if (true) throw new ErrorSemantico("Solo se admiten expresiones booleanas: "+at.type);}
                }

                sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();

                for(Attributes a : att.atts)
                {
                        System.out.println(a.code);
                }

                lbel = CGUtils.newLabel();
                cBlock.addInst(PCodeInstruction.OpCode.JMF,lbel);

                cBlock.addComment("Inicio Bloque de instrucciones IF");
    jj_consume_token(tTHEN);
    instrucciones(cbloque);
cBlock.addBlock(cbloque);
                cbloque=new CodeBlock();
                cBlock.addComment("Fin Bloque de instrucciones IF");
                cBlock.addInst(PCodeInstruction.OpCode.JMP,endLabel);
                cBlock.addLabel(lbel);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tELSIF:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_8;
      }
      jj_consume_token(tELSIF);
      expresion(at, cBlock);
if(at.type==Symbol.Types.ARRAY)
                {
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("El array tienen que devolver un booleano: "+at.type);}
                        }
                }
                else if(at.type== Symbol.Types.FUNCTION)
                {
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("La funcion tienen que devolver un booleano: "+at.type);}
                        }
                }
                else if(at.type!=Symbol.Types.BOOL)
                {
                        {if (true) throw new ErrorSemantico("Solo se admiten expresiones booleanas: "+at.type);}
                }
                sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();

                lbel = CGUtils.newLabel();
                cBlock.addInst(PCodeInstruction.OpCode.JMF,lbel);
                cBlock.addComment("Inicio Bloque de instrucciones ELSIF");
      jj_consume_token(tTHEN);
      instrucciones(cbloque);
cBlock.addBlock(cbloque);
                cbloque=new CodeBlock();
                cBlock.addComment("Fin Bloque de instrucciones ELSIF");
                cBlock.addInst(PCodeInstruction.OpCode.JMP,endLabel);
                cBlock.addLabel(lbel);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tELSE:{
      jj_consume_token(tELSE);
cBlock.addComment("Inicio Bloque de instrucciones ELSE");
      instrucciones(cbloque);
cBlock.addBlock(cbloque);
                cbloque=new CodeBlock();
                cBlock.addComment("Fin Bloque de instrucciones ELSE");
                cBlock.addInst(PCodeInstruction.OpCode.JMP,endLabel);
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(tENDIF);
cBlock.addLabel(endLabel);
}

  static final public void inst_while(Attributes att,CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();

        CodeBlock cbloque=new CodeBlock();

        String initLabel = CGUtils.newLabel();
        String endLabel = CGUtils.newLabel();
    jj_consume_token(tWHILE);
cBlock.addLabel(initLabel);
    expresion(at, cBlock);
if(at.type==Symbol.Types.ARRAY || at.type==Symbol.Types.FUNCTION)
                {
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("Solo se admiten expresiones booleanas: "+at.type);}
                        }
                }
                else if(at.type!=Symbol.Types.BOOL)
                {
                        {if (true) throw new ErrorSemantico("Solo se admiten expresiones booleanas: "+at.type);}
                }
                sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);

                cBlock.addInst(PCodeInstruction.OpCode.JMF,endLabel);
    jj_consume_token(tLOOP);
    instrucciones(cbloque);
    jj_consume_token(tENDLOOP);
cBlock.addComment("Inicio Bloque de instrucciones While");
                cBlock.addBlock(cbloque);
                cBlock.addComment("Fin Bloque de instrucciones While");
                cBlock.addInst(PCodeInstruction.OpCode.JMP,initLabel);
                cBlock.addLabel(endLabel);
                //System.err.println("Expresion while condicion: " + att);

}

  static final public void inst_return(Attributes att,CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();
    jj_consume_token(tRETURN);
    expresion(at, cBlock);
try{
                        Symbol S = st.getSymbol(tipoReturn.get(tipoReturn.size()-1).image);
                        sf.add_to_atts(att,at);

                        if(S.type != Symbol.Types.FUNCTION){
                                {if (true) throw new ErrorSemantico("Solo se puede hacer return en funciones");}
                        }
                        if(at.type == Symbol.Types.FUNCTION)
                        {
                                if(at.extraType!=((SymbolFunction)S).returnType)
                                {
                                        {if (true) throw new ErrorSemantico("Error de tipos en return");}
                                }
                        }
                        else if(at.type != ((SymbolFunction)S).returnType)
                        {

                                {if (true) throw new ErrorSemantico("Error de tipos en return");}
                        }

                        at = new Attributes();

                        cBlock.addInst(PCodeInstruction.OpCode.CSF);
                } catch(SymbolNotFoundException ex) {
                        {if (true) throw new ErrorSemantico("Error semantico. Funcion no encontrada");}
                }
}

  static final public void inst_null(Attributes att,CodeBlock cBlock) throws ParseException {
    jj_consume_token(tNULL);
cBlock.addComment("Bloque sin instrucciones");
}

  static final public void expresion(Attributes att, CodeBlock cBlock) throws ParseException {Boolean esBool = false;
        Attributes at = new Attributes();
        CodeBlock cExp = new CodeBlock();
    relacion(at, cExp);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();

                cBlock.addBlock(cExp);
                cExp = new CodeBlock();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAND:
    case tOR:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tAND:{
        label_9:
        while (true) {
          jj_consume_token(tAND);
att.type = Symbol.Types.BOOL;
                esBool = true;
          relacion(at, cExp);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();

                cBlock.addBlock(cExp);
                cBlock.addInst(PCodeInstruction.OpCode.AND);
                cExp = new CodeBlock();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case tAND:{
            ;
            break;
            }
          default:
            jj_la1[25] = jj_gen;
            break label_9;
          }
        }
        break;
        }
      case tOR:{
        label_10:
        while (true) {
          jj_consume_token(tOR);
att.type = Symbol.Types.BOOL;
                esBool = true;
          relacion(at, cExp);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();

                cBlock.addBlock(cExp);
                cBlock.addInst(PCodeInstruction.OpCode.OR);
                cExp = new CodeBlock();
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case tOR:{
            ;
            break;
            }
          default:
            jj_la1[26] = jj_gen;
            break label_10;
          }
        }
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      ;
    }
// ( 2+3+4) + 5 + (2+3)
                // Expresion
                //  (2+3+4)
                //   5
                //  (2+3)
                if(esBool)
                {
                         for(Attributes a : att.atts)
                         {
                                //System.err.println(a.type);
                                if(a.type == Symbol.Types.FUNCTION || a.type == Symbol.Types.ARRAY){
                                        if(a.extraType!=Symbol.Types.BOOL)
                                        {
                                                {if (true) throw new ErrorSemantico("Error de tipos");}
                                        }
                                        if(a.type == Symbol.Types.ARRAY){
                                                Attributes aux = a.atts.get(0);
                                                for(int i=0; i<5 && aux.atts.size()>0; i++)
                                                {
                                                        aux = aux.atts.get(0);
                                                        //System.err.println(aux.type);
                                                }
                                                if(aux.type!=Symbol.Types.INT)
                                                {
                                                        {if (true) throw new ErrorSemantico("No puedes comparar un array entero con un booleano");}
                                                }
                                        }
                                } else{
                                        if(a.type!=Symbol.Types.BOOL)
                                        {
                                                {if (true) throw new ErrorSemantico("Error de tipos");}
                                        }
                                }
                         }
                         //System.out.println();
                }
}

  static final public void relacion(Attributes att, CodeBlock cBlock) throws ParseException {//Attributes atTypes = new Attributes();
        Boolean tieneOpInts = null;
        Attributes at = new Attributes();
        CodeBlock cRel = new CodeBlock();
    expresion_simple(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tGE:
    case tLE:
    case tNEQ:
    case tEQ:
    case tGT:
    case tLS:{
      tieneOpInts = operador_relacional(cRel);
      expresion_simple(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
cBlock.addBlock(cRel);

                if(tieneOpInts!=null)
                {
                        att.type = Symbol.Types.BOOL;
                        if(tieneOpInts)
                        {
                                //System.err.println("Operador relacional: " + att);
                                for(Attributes a : att.atts)
                                {
                                        if (a.type==Symbol.Types.ARRAY || a.type==Symbol.Types.FUNCTION)
                                        {
                                                if(a.extraType!=Symbol.Types.INT)
                                                {
                                                        {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban integers en relacion: "+a.type);}
                                                }
                                        } else if(a.type!=Symbol.Types.INT)
                                        {
                                                {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban integers en relacion: "+a.type);}
                                        }
                                }
                        } else {
                                if(at.type != Symbol.Types.UNDEFINED)
                                {
                                        Attributes a2 = att.atts.get(att.atts.size()-2);
                                        if(a2.type == Symbol.Types.FUNCTION || a2.type == Symbol.Types.ARRAY)
                                        {
                                                if(a2.extraType!=at.type)
                                                {
                                                        {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban el mismo tipo en relacion: " + a2.extraType + " y "+ at.type);}
                                                }
                                        } else if(at.type == Symbol.Types.FUNCTION || at.type == Symbol.Types.ARRAY)
                                        {
                                                if(a2.type!=at.extraType)
                                                {
                                                        {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban el mismo tipo en relacion: " + a2.type + " y "+ at.extraType);}
                                                }
                                        }
                                        else if(a2.type!=at.type)
                                        {
                                                {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban el mismo tipo en relacion: " + a2.type + " y "+ at.type);}
                                        }
                                }
                        }
                }
}

  static final public Boolean operador_relacional(CodeBlock cBlock) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tEQ:{
      jj_consume_token(tEQ);
cBlock.addInst(PCodeInstruction.OpCode.EQ);{if ("" != null) return false;}
      break;
      }
    case tLS:{
      jj_consume_token(tLS);
cBlock.addInst(PCodeInstruction.OpCode.LT);{if ("" != null) return true;}
      break;
      }
    case tGT:{
      jj_consume_token(tGT);
cBlock.addInst(PCodeInstruction.OpCode.GT);{if ("" != null) return true;}
      break;
      }
    case tLE:{
      jj_consume_token(tLE);
cBlock.addInst(PCodeInstruction.OpCode.LTE);{if ("" != null) return true;}
      break;
      }
    case tGE:{
      jj_consume_token(tGE);
cBlock.addInst(PCodeInstruction.OpCode.GTE);{if ("" != null) return true;}
      break;
      }
    case tNEQ:{
      jj_consume_token(tNEQ);
cBlock.addInst(PCodeInstruction.OpCode.NEQ);{if ("" != null) return false;}
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public void expresion_simple(Attributes att, CodeBlock cBlock) throws ParseException {boolean esInt=false;
        Attributes at = new Attributes();
        CodeBlock cOP = new CodeBlock();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tADD:
    case tSUB:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tADD:{
        jj_consume_token(tADD);
        break;
        }
      case tSUB:{
        jj_consume_token(tSUB);
cOP.addInst(PCodeInstruction.OpCode.NGI);
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
esInt=true;att.type=Symbol.Types.INT;
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      ;
    }
    termino(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();

                cBlock.addBlock(cOP);
                cOP = new CodeBlock();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tADD:
      case tSUB:{
        ;
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tADD:{
        jj_consume_token(tADD);
cOP.addInst(PCodeInstruction.OpCode.PLUS);
        break;
        }
      case tSUB:{
        jj_consume_token(tSUB);
cOP.addInst(PCodeInstruction.OpCode.SBT);
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      termino(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();
                att.type = Symbol.Types.INT;
                //System.err.println("Expresion simple: " + att);
                for(Attributes a : att.atts)
                {
                        if(a.type == Symbol.Types.FUNCTION || a.type == Symbol.Types.ARRAY)
                        {
                                if(a.extraType!=Symbol.Types.INT)
                                {
                                        {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban integers en expresion simple: " + a.type);}
                                }
                        } else if(a.type!=Symbol.Types.INT)
                        {
                                {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban integers en expresion simple: " + a.type);}
                        }
                }

                cBlock.addBlock(cOP);
                cOP = new CodeBlock();
    }
}

  static final public void termino(Attributes att, CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();
        CodeBlock opMUL = new CodeBlock();
    factor(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tDIV:
      case tMUL:
      case tMOD:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_12;
      }
      operador_multiplicativo(opMUL);
      factor(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                att.type = Symbol.Types.INT;
                at = new Attributes();

                for(Attributes a : att.atts)
                {
                        if(a.type == Symbol.Types.FUNCTION || a.type == Symbol.Types.ARRAY)
                        {
                                if(a.extraType!=Symbol.Types.INT)
                                {
                                        {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban integers en termino: " + att.atts.get(0).type);}
                                }
                        } else if(a.type!=Symbol.Types.INT)
                        {
                                {if (true) throw new ErrorSemantico("Error de tipos. Se esperaban integers en termino: " + att.atts.get(0).type);}
                        }
                }

                cBlock.addBlock(opMUL);
                opMUL = new CodeBlock();
    }
}

  static final public void operador_multiplicativo(CodeBlock cBlock) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tMUL:{
      jj_consume_token(tMUL);
cBlock.addInst(PCodeInstruction.OpCode.TMS);
      break;
      }
    case tMOD:{
      jj_consume_token(tMOD);
cBlock.addInst(PCodeInstruction.OpCode.MOD);
      break;
      }
    case tDIV:{
      jj_consume_token(tDIV);
cBlock.addInst(PCodeInstruction.OpCode.DIV);
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void factor(Attributes att, CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:
    case tSUB:
    case tTRUE:
    case tFALSE:
    case tINT2CHAR:
    case tCHAR2INT:
    case tCONST_CHAR:
    case tCONST_INT:
    case tCONST_STRING:
    case tID:{
      primario(at, cBlock);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                at = new Attributes();
      break;
      }
    case tNOT:{
      jj_consume_token(tNOT);
      primario(at, cBlock);
att.type = Symbol.Types.BOOL;
                sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
                if(at.type == Symbol.Types.ARRAY)
                {
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("El array tienen que devolver un booleano: "+at.type);}
                        }
                }
                else if(at.type == Symbol.Types.FUNCTION)
                {
                        if(at.extraType!=Symbol.Types.BOOL)
                        {
                                {if (true) throw new ErrorSemantico("La funcion tienen que devolver un booleano: "+at.type);}
                        }
                }
                else if(at.type!=Symbol.Types.BOOL)
                {
                        {if (true) throw new ErrorSemantico("Solo se admiten expresiones booleanas: "+at.type);}
                }
                at = new Attributes();

                cBlock.addInst(PCodeInstruction.OpCode.NGB);
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void primario(Attributes att, CodeBlock cBlock) throws ParseException {Attributes at = new Attributes();

        Token t;
        Symbol S;
        boolean minus = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tAP:{
      jj_consume_token(tAP);
      expresion(at, cBlock);
      jj_consume_token(tCP);
sf.add_to_atts(att,at);
                sf.heredar_valores(att,at);
      break;
      }
    case tINT2CHAR:{
      jj_consume_token(tINT2CHAR);
      jj_consume_token(tAP);
      expresion(at, cBlock);
      jj_consume_token(tCP);
if(at.type!=Symbol.Types.INT)
                {
                        {if (true) throw new ErrorSemantico("int2char solo acepta enteros");}
                }
                if(at.atts.size()!=1){
                        {if (true) throw new ErrorSemantico("int2char solo acepta un entero");}
                }

                //cBlock.addInst(PCodeInstruction.OpCode.ASG);

                sf.asignar_valores(att,at,at.code,Symbol.Types.CHAR, Symbol.ParameterClass.VAL, st.level, true);
                sf.heredar_valores(att,at);
      break;
      }
    case tCHAR2INT:{
      jj_consume_token(tCHAR2INT);
      jj_consume_token(tAP);
      expresion(at, cBlock);
      jj_consume_token(tCP);
if(at.type!=Symbol.Types.CHAR)
                {
                        {if (true) throw new ErrorSemantico("char2int solo acepta caracteres");}
                }
                if(at.atts.size()!=1){
                        {if (true) throw new ErrorSemantico("char2int solo acepta un caracter");}
                }

                sf.asignar_valores(att,at,"char2int(" + at.code + ")",Symbol.Types.INT, Symbol.ParameterClass.VAL, st.level,true);
                sf.heredar_valores(att,at);
      break;
      }
    case tID:{
      t = jj_consume_token(tID);
try
                {
                        t.image = t.image.toLowerCase();
                        S = st.getSymbol(t.image);
                }
                catch(SymbolNotFoundException ex)
                {
                        {if (true) throw new ErrorSemantico(t.image + " no existe.");}
                }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tAP:{
        jj_consume_token(tAP);
        function_call(at,cBlock,S);
        jj_consume_token(tCP);
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        ;
      }
sf.cambiarTipos(at, S);
                        sf.asignar_valores(att,at,t.image,S.type, S.parClass, st.level,false);
                        sf.checkPrimarioIds(at);


                        if(S instanceof SymbolProcedure)
                        {
                                SymbolProcedure SP = (SymbolProcedure) S;
                                cBlock.addOSFInst(CGUtils.getInvocDir(),st.level-S.nivel,SP.etiq);
                        }
                        else if(S instanceof SymbolFunction)
                        {
                                SymbolFunction SF = (SymbolFunction) S;
                                cBlock.addOSFInst(CGUtils.getInvocDir(),st.level-S.nivel,SF.etiq);
                        }
                        else if(S.type == Symbol.Types.ARRAY)
                        {
                                SymbolArray SA = (SymbolArray) S;

                                //cBlock.addComment(at.type+"");

                                if(at.type==Symbol.Types.ARRAY)
                                {
                                        cBlock.addComment("Array completo 2");
                                        //cBlock.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);

                                        cBlock.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);

                                        if(S.parClass == Symbol.ParameterClass.REF)
                                        {
                                                cBlock.addInst(PCodeInstruction.OpCode.DRF);
                                        }
                                }else
                                {
                                        cBlock.addComment("Componente Array");
                                        if(SA.minInd<0)
                                        {
                                                cBlock.addInst(PCodeInstruction.OpCode.STC,-SA.minInd);
                                                cBlock.addInst(PCodeInstruction.OpCode.NGI);
                                                cBlock.addInst(PCodeInstruction.OpCode.SBT);
                                        }
                                        else if(SA.minInd>0)
                                        {
                                                cBlock.addInst(PCodeInstruction.OpCode.STC,SA.minInd);
                                                cBlock.addInst(PCodeInstruction.OpCode.SBT);
                                        }

                                        cBlock.addInst(PCodeInstruction.OpCode.SRF,(st.level - S.nivel),(int)S.dir);

                                        if(S.parClass == Symbol.ParameterClass.REF)
                                        {
                                                cBlock.addInst(PCodeInstruction.OpCode.DRF);
                                        }

                                        if(at.type!=Symbol.Types.ARRAY)
                                        {
                                                cBlock.addInst(PCodeInstruction.OpCode.PLUS);
                                                cBlock.addInst(PCodeInstruction.OpCode.DRF);
                                        }
                                }





                                at = new Attributes();


                        }
                        else
                        {
                                cBlock.addInst(PCodeInstruction.OpCode.SRF,st.level-S.nivel,(int)S.dir);
                                cBlock.addInst(PCodeInstruction.OpCode.DRF);
                        }
      break;
      }
    case tSUB:
    case tCONST_INT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tSUB:{
        jj_consume_token(tSUB);
minus = true;
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      t = jj_consume_token(tCONST_INT);
cBlock.addInst(PCodeInstruction.OpCode.STC, Integer.parseInt(t.image));
                if(minus){cBlock.addInst(PCodeInstruction.OpCode.NGI);}
                sf.asignar_valores(att,at,t.image,Symbol.Types.INT, Symbol.ParameterClass.VAL, st.level,true);
      break;
      }
    case tCONST_CHAR:{
      t = jj_consume_token(tCONST_CHAR);
char charValue = t.image.charAt(1);
                cBlock.addInst(PCodeInstruction.OpCode.STC, (int) charValue);
                sf.asignar_valores(att,at,t.image,Symbol.Types.CHAR, Symbol.ParameterClass.VAL, st.level,true);
      break;
      }
    case tCONST_STRING:{
      t = jj_consume_token(tCONST_STRING);
// cBlock.addInst(PCodeInstruction.OpCode.STC, Integer.parseInt(t.image));
                sf.asignar_valores(att,at,t.image,Symbol.Types.STRING, Symbol.ParameterClass.VAL, st.level,true);
      break;
      }
    case tTRUE:{
      t = jj_consume_token(tTRUE);
cBlock.addInst(PCodeInstruction.OpCode.STC, 1);
                sf.asignar_valores(att,at,"true",Symbol.Types.BOOL, Symbol.ParameterClass.VAL, st.level,true);
      break;
      }
    case tFALSE:{
      t = jj_consume_token(tFALSE);
cBlock.addInst(PCodeInstruction.OpCode.STC, 0);
                sf.asignar_valores(att,at,"false",Symbol.Types.BOOL, Symbol.ParameterClass.VAL, st.level,true);
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void function_call(Attributes att,CodeBlock cBloque,Symbol S) throws ParseException {Attributes at = new Attributes();
        CodeBlock cBlock = new CodeBlock();
        int i=0;
    expresion(at, cBlock);
//System.out.println(at.parClass);

        //System.out.println(at.toString());

        if(S instanceof SymbolProcedure)
        {
                SymbolProcedure SP = (SymbolProcedure) S;
                //System.out.println(SP.parList.get(i).parClass);
                at.parClass = SP.parList.get(i).parClass;
                i++;
        }

        if(S instanceof SymbolFunction)
        {
                SymbolFunction SF = (SymbolFunction) S;
                //System.out.println(SF.parList.get(i).parClass);
                at.parClass = SF.parList.get(i).parClass;
                i++;
        }

        sf.add_to_atts(att,at);
        sf.heredar_valores(att,at);

        if(at.esConstante&&at.parClass==Symbol.ParameterClass.REF)
        {
                {if (true) throw new ErrorSemantico("No puedes pasar una constante como valor por referencia");}
        }

        //System.out.println(at.parClass);	

        if(at.type==Symbol.Types.ARRAY&&at.parClass==Symbol.ParameterClass.VAL)
        {
                SymbolArray SA = null;

                try
                {
                        SA = (SymbolArray)st.getSymbol(at.code);
                } catch(SymbolNotFoundException ex)
                {
                        {if (true) throw new ErrorSemantico(at.code+" no existe");}
                }

                for(int j=1;j<SA.maxInd-SA.minInd+1;j++)
                {
                        cBlock.addInst(PCodeInstruction.OpCode.SRF,(st.level - SA.nivel),(int)SA.dir+j);
                        cBlock.addInst(PCodeInstruction.OpCode.DRF);
                }
        }

        cBloque.addBlock(cBlock);
        cBlock = new CodeBlock();

        at = new Attributes();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tCOMA:{
        ;
        break;
        }
      default:
        jj_la1[41] = jj_gen;
        break label_13;
      }
      jj_consume_token(tCOMA);
      expresion(at, cBlock);
if(S instanceof SymbolProcedure)
        {
                SymbolProcedure SP = (SymbolProcedure) S;
                //System.out.println(SP.parList.get(i).parClass);
                at.parClass = SP.parList.get(i).parClass;
                i++;
        }

        if(S instanceof SymbolFunction)
        {
                SymbolFunction SF = (SymbolFunction) S;
                //System.out.println(SF.parList.get(i).parClass);
                at.parClass = SF.parList.get(i).parClass;
                i++;
        }

        sf.add_to_atts(att,at);
        sf.heredar_valores(att,at);

        if(at.esConstante&&at.parClass==Symbol.ParameterClass.REF)
        {
                {if (true) throw new ErrorSemantico("No puedes pasar una constante como valor por referencia");}
        }

        //System.out.println(at.parClass);
        if(at.type==Symbol.Types.ARRAY&&at.parClass==Symbol.ParameterClass.VAL)
        {
                SymbolArray SA = null;

                try
                {
                        SA = (SymbolArray)st.getSymbol(at.code);
                } catch(SymbolNotFoundException ex)
                {
                        {if (true) throw new ErrorSemantico(at.code+" no existe");}
                }

                for(int j=1;j<SA.maxInd-SA.minInd+1;j++)
                {
                        cBlock.addInst(PCodeInstruction.OpCode.SRF,(st.level - SA.nivel),(int)SA.dir+j);
                        cBlock.addInst(PCodeInstruction.OpCode.DRF);
                }
        }

        cBloque.addBlock(cBlock);
        cBlock = new CodeBlock();

        at = new Attributes();
    }

}

  static final public void tipo_variable(Attributes atTypes, Attributes atIsArray) throws ParseException {Token i;
        Boolean esNegativo = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tARRAY:{
      jj_consume_token(tARRAY);
      jj_consume_token(tAP);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tSUB:{
        jj_consume_token(tSUB);
esNegativo=true;
        break;
        }
      default:
        jj_la1[42] = jj_gen;
        ;
      }
      i = jj_consume_token(tCONST_INT);
if(esNegativo)  atTypes.inicio = -Integer.parseInt(i.image);
                        else atTypes.inicio = Integer.parseInt(i.image);
                        esNegativo = false;

                        //at.parList.add(new Symbol(i.image,Symbol.Types.INT));

      jj_consume_token(64);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case tSUB:{
        jj_consume_token(tSUB);
esNegativo=true;
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        ;
      }
      i = jj_consume_token(tCONST_INT);
if(esNegativo)  atTypes.fin = -Integer.parseInt(i.image);
                        else atTypes.fin = Integer.parseInt(i.image);
                        // at.parList.add(new Symbol(i.image,Symbol.Types.INT));
                        atTypes.type = Symbol.Types.ARRAY;
                        esNegativo = false;
      jj_consume_token(tCP);
      jj_consume_token(tOF);
      tipo_variable_simple(atIsArray);
      break;
      }
    case tBOOL:
    case tCHAR:
    case tINT:{
      tipo_variable_simple(atTypes);
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void tipo_variable_simple(Attributes at) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case tBOOL:{
      jj_consume_token(tBOOL);
at.type = Symbol.Types.BOOL;
      break;
      }
    case tCHAR:{
      jj_consume_token(tCHAR);
at.type = Symbol.Types.CHAR;
      break;
      }
    case tINT:{
      jj_consume_token(tINT);
at.type = Symbol.Types.INT;
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public alikeTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[46];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x800,0x800,0x0,0x800,0x0,0x800,0x800,0x38041000,0x0,0x400000,0x40000000,0x0,0x40000000,0x0,0x0,0x40000000,0x40000000,0x4000000,0x38041000,0x40000000,0x40000000,0x0,0x4000,0x8000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x42000000,0x40000000,0x0,0x40000000,0x0,0x0,0x0,0x780,0x380,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x8000000,0x20000,0x20000,0x8000000,0x20000,0x8000000,0x20000,0x20000,0x80d0000,0x8000000,0x0,0x0,0x4000,0x0,0x4000,0x4000,0x0,0x0,0x0,0x80d0000,0x0,0x0,0x1,0x0,0x0,0x100,0x200,0x300,0x300,0x7e,0x7e,0xc00,0xc00,0xc00,0xc00,0xb000,0xb000,0xff00800,0x0,0x800,0xff00800,0x4000,0x800,0x800,0x0,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public alike(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public alike(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new alikeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public alike(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new alikeTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new alikeTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public alike(alikeTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(alikeTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[65];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 46; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 65; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
